spring.application.name=requestructure-api

# MySQL (variables de entorno para despliegue real)
spring.datasource.url=${DB_URL:jdbc:mysql://54.152.73.116:3306/requestructure_db?createDatabaseIfNotExist=true&serverTimezone=Europe/Madrid}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=${PORT:8080}
